#!/usr/bin/env python3
# Copyright (C) 2021 Corexalys.
#
# This file is part of rs3f.
#
# rs3f is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rs3f is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rs3f.  If not, see <https://www.gnu.org/licenses/>.
from argparse import ArgumentParser
import os
import re

from rs3f_common import get_authorized_keys_path, get_home_path

RE_PUBLIC_KEY = re.compile(
    r"(?P<key>ssh-[^\s]+ [a-zA-Z0-9+/]+=*)(?: (?P<username>[^\s]+))?"
)


def main():
    parser = ArgumentParser()
    parser.add_argument(
        "container_name",
        help="A comma-separated list of container names",
    )
    args = parser.parse_args()

    to_add = set()

    for container in args.container_name.split(","):
        container = container.strip()
        if not container:
            continue
        if not os.path.exists(get_home_path(container)):
            raise ValueError(f"Container '{container}' does not exist")

        print(f"{container}:")
        path = get_authorized_keys_path(container)
        with open(path, "r") as authorized_file:
            for line in authorized_file:
                if not line.strip() or line.strip().startswith("#"):
                    continue
                _, _, user = line.split(" ")
                print(f"- {user}")

    print("DONE")


if __name__ == "__main__":
    main()
