#!/usr/bin/env python3
# Copyright (C) 2021 Corexalys.
#
# This file is part of rs3f.
#
# rs3f is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rs3f is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rs3f.  If not, see <https://www.gnu.org/licenses/>.
from argparse import ArgumentParser
import os
import re
import pwd

from rs3f_common import HOME_DIR


def main():
    user_names = {pw.pw_name for pw in pwd.getpwall()}

    for entry in os.scandir(HOME_DIR):
        if entry.is_dir and entry.name in user_names:
            print(entry.name)


if __name__ == "__main__":
    main()
